# Generated by Django 2.2.1 on 2019-05-27 03:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(default='asdf'),
        ),
    ]
