# Generated by Django 2.1 on 2019-05-01 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insta',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insta',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='insta',
            name='image',
            field=models.ImageField(upload_to='timeline_photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='insta',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
