# Generated by Django 2.1 on 2019-05-01 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20190501_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insta',
            options={'ordering': ['-created']},
        ),
    ]
