# Generated by Django 2.1 on 2019-04-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20190429_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
