version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
#      - "8000:80"
      - "80:80"
    volumes:
      - ./.config/nginx:/etc/nginx/conf.d
    depends_on:
      - django
  django:
    build:
      context: .
      dockerfile: .compose/django/Dockerfile
    expose:
      - "8011"

