# Generated by Django 2.2.1 on 2019-05-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190513_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True),
        ),
    ]
