# Generated by Django 2.2.1 on 2019-05-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20190515_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=30, unique=True),
        ),
    ]
