"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-3(tjoki0@y7hjv0ak6j--*5u8xgz&6v)2&1tw2*&%5&%#d)a3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'multi',
        # USERNAME이 없으면 로그인 시도를 하면 계정명으로 로그인 시도를 한다
        'USER': 'wps_master',
        'PASSWORD': 'ghd941322',
        'HOST': 'multi.cakloest4jdx.ap-northeast-2.rds.amazonaws.com',
        'PORT': '5432',
    },
    'read1': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'multi',
        # USERNAME이 없으면 로그인 시도를 하면 계정명으로 로그인 시도를 한다
        'USER': 'wps_master',
        'PASSWORD': 'ghd941322',
        'HOST': 'mulit-read1.cakloest4jdx.ap-northeast-2.rds.amazonaws.com',
        'PORT': '5432',
    },
    'read2': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'multi',
        # USERNAME이 없으면 로그인 시도를 하면 계정명으로 로그인 시도를 한다
        'USER': 'wps_master',
        'PASSWORD': 'ghd941322',
        'HOST': 'multi-read2.cakloest4jdx.ap-northeast-2.rds.amazonaws.com',
        'PORT': '5432',
    },
    'user': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'multi_master',
        # USERNAME이 없으면 로그인 시도를 하면 계정명으로 로그인 시도를 한다
        'USER': 'wps_master',
        'PASSWORD': 'ghd941322',
        'HOST': 'multidb2.cakloest4jdx.ap-northeast-2.rds.amazonaws.com',
        'PORT': '5432',
    }
}

DATABASE_ROUTERS = [
    'config.user_router.UserRouter',
    'config.master_slave_router.MasterSlaveRouter',

]

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



INTERNAL_IPS = ['127.0.0.1']

DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
