# Generated by Django 2.2.2 on 2019-07-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foriegn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.ManyToManyField(related_name='authors', to='foriegn.Author'),
        ),
    ]
